name: cdp_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.4.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.2
  file_picker: ^3.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^8.1.3
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.4.0
  purchases_flutter: ^3.4.0
  lint: ^1.5.3
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  page_transition: ^2.0.2
  path_provider: ^2.0.2
  syncfusion_flutter_pdf: ^19.2.48-beta
  syncfusion_flutter_signaturepad: ^19.1.67-beta
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: SocialMediaIcons
      fonts:
        - asset: assets/icons/SocialMediaIcons.ttf
